# Reference Link for deploying on Firebase
# https://www.skcript.com/svr/deploying-react-apps-to-firebase-hosting-with-github-actions/#:~:text=Configuration%20of%20Firebase%20Service%20Account%20in%20Github&text=Navigate%20to%20Project%20Settings%20from%20the%20sidebar.&text=Copy%20the%20contents%20of%20the%20downloaded%20file.&text=Click%20on%20the%20%E2%80%9CNew%20secret%E2%80%9D%20button.&text=After%20saving%2C%20we're%20all,push%20to%20your%20GitHub%20repository.

name: Deploy to Live Channel

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CONTACTS_APP_EF97E }}'
          channelId: live
          projectId: contacts-app-ef97e
          expires: 30d